-- https://school.programmers.co.kr/learn/courses/30/lessons/157341
SELECT
    A.CAR_ID
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
    LEFT JOIN CAR_RENTAL_COMPANY_CAR AS B ON A.CAR_ID = B.CAR_ID
WHERE
    B.CAR_TYPE = '세단'
    AND A.START_DATE LIKE '%-10-%'
GROUP BY
    CAR_ID
ORDER BY
    CAR_ID DESC;