-- https://school.programmers.co.kr/learn/courses/30/lessons/151141
-- WITH문 잘 사용하기
-- CASE문 잘 사용하기
-- JOIN 조건 두 개 주는 것에 주목
WITH VALUE AS(
    SELECT
        CAR.DAILY_FEE,
        CAR.CAR_TYPE,
        HIS.HISTORY_ID,
        DATEDIFF(END_DATE, START_DATE) + 1 AS PERIOD,
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE 'NONE'
        END AS DURATION_TYPE
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HIS
        INNER JOIN CAR_RENTAL_COMPANY_CAR AS CAR ON HIS.CAR_ID = CAR.CAR_ID
    WHERE
        CAR.CAR_TYPE = '트럭'
)
SELECT
    VALUE.HISTORY_ID,
    ROUND(
        VALUE.DAILY_FEE * VALUE.PERIOD *(100 - IFNULL(PLAN.DISCOUNT_RATE, 0)) / 100
    ) AS FEE
FROM
    VALUE
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN ON VALUE.DURATION_TYPE = PLAN.DURATION_TYPE
    AND VALUE.CAR_TYPE = PLAN.CAR_TYPE
ORDER BY
    FEE DESC,
    VALUE.HISTORY_ID DESC