-- https://school.programmers.co.kr/learn/courses/30/lessons/133026
-- JOIN 후 SELECT 어떻게 하는지, ORDERBY 조건 어떻게 주는가에 주목
SELECT
    INGREDIENT_TYPE,
    SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM
    FIRST_HALF AS A
    LEFT JOIN ICECREAM_INFO AS B ON A.FLAVOR = B.FLAVOR
GROUP BY
    INGREDIENT_TYPE
ORDER BY
    TOTAL_ORDER ASC;