-- https://school.programmers.co.kr/learn/courses/30/lessons/144855
SELECT
    A.CATEGORY,
    SUM(SALES) AS TOTAL_SALES
FROM
    BOOK AS A
    INNER JOIN BOOK_SALES AS B ON A.BOOK_ID = B.BOOK_ID
WHERE
    SALES_DATE LIKE '2022-01-%'
GROUP BY
    A.CATEGORY
ORDER BY
    A.CATEGORY