-- https://school.programmers.co.kr/learn/courses/30/lessons/164668
SELECT
    B.USER_ID,
    B.NICKNAME,
    SUM(PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_BOARD AS A
    JOIN USED_GOODS_USER AS B ON A.WRITER_ID = B.USER_ID
WHERE
    A.STATUS = 'DONE'
GROUP BY
    A.WRITER_ID
HAVING
    SUM(PRICE) >= 700000
ORDER BY
    TOTAL_SALES